
-- ALTERAR TABELA MEDICOS:
ALTER TABLE medicos ADD ativo TINYINT;
UPDATE medicos SET ativo = 1;
ALTER TABLE medicos MODIFY COLUMN ativo TINYINT NOT NULL;

-- ALTERAR TABELA PACIENTES:
ALTER TABLE pacientes ADD ativo TINYINT;
UPDATE pacientes SET ativo = 1;
ALTER TABLE pacientes MODIFY COLUMN ativo TINYINT NOT NULL;

